version: '2.1'

networks:
  default:
    name: nginx-proxy
    external: true

volumes:
  acme: # /etc/acme.sh
  html: # Nginx wwww (http challenge for SSL)
  conf: # Nginx config (global or proxy wide)
  vhost: # Nginx config (per VIRTUAL_HOST)
  certs: # SSL files from LetsEncrypt
    external: true

services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html

  gen:
    build: .
    command: -notify-sighup proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on:
      - proxy
      - gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"

  ssl:
    image: nginxproxy/acme-companion
    environment:
      - DEFAULT_EMAIL
    depends_on:
      - proxy
      - gen
    volumes:
      - acme:/etc/acme.sh
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
